---
name: DBIx-Class-RandomColumns
version: 0.01
author: ~
abstract: Implicit random columns
license: perl
requires:
  DBIx::Class: 0.05
recommends:
  DBD::SQLite: 1.11
build_requires:
  File::Temp: 0
  Test::More: 0
provides:
  DBIx::Class::RandomColumns:
    file: lib/DBIx/Class/RandomColumns.pm
    version: 0.01
generated_by: Module::Build version 0.261
